name: Test deployment - projectInfo

on:
  # repository_dispatch:
  #   types:
  #     - test-rebuild-docs-site
  pull_request:
    branches:
      - main
    paths:
      - 'projectInfo/**'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change directory
        run: cd projectInfo
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install docusaurus
        run: npm install -g docusaurus
      - name: Test build website
        run: npm run build